### ISSUE TITLE
Code for Photo Upload

### ISSUE THREAD

**Issue by msgadi** [samjudson/flickrnet-samples#1]
hey sam can you please upload a demo code for flicker photo upload from web.

**Comment by samjudson** [comment]
What are you stuck with? The upload to a web site part, or the upload to Flickr part?

The upload to Flickr is identical to any other example once you have the Stream of the file.

There are many examples of how to upload a file in ASP.Net web forms, e.g. https://support.microsoft.com/en-us/kb/323246

**Comment by msgadi** [comment]
Hey sam I was talking about the demo for Image upload to Flickr.But digging deep into your library I found the solution for my prob. Thanks alot for making such a nice library man!!.

**Comment by msgadi** [comment]
When I try to upload photo to Flickr, I authorize it from Flickr authentication page and photo get uploaded.The problem currently I am facing is need to authorize every time I upload though the tokens and all are in cookies(I am using the FlickrManager.cs class given in your sample),can you please let meknow what I am missing so that I need to authorize it every time I want to upload the photo.**_Please find the below code for reference._**

```
public partial class RecentFeeds : System.Web.UI.Page
{
    private DataTable dtphotos;
    private string UserID = "139607722@N06";

    protected void Page_Load(object sender, EventArgs e)
    {
        // The request token is stored in session - if it isn't present then we do nothing
        if (Request.QueryString["oauth_verifier"] != null && Session["RequestToken"] != null)
        {
            Flickr f = FlickrManager.GetInstance();
            OAuthRequestToken requestToken = Session["RequestToken"] as OAuthRequestToken;
            try
            {
                OAuthAccessToken accessToken = f.OAuthGetAccessToken(requestToken, Request.QueryString["oauth_verifier"]);
                FlickrManager.OAuthToken = accessToken;
                string callbackThumbID = f.UploadPicture(fileName, title, string.Empty, string.Empty, true, false, false);

                //other photoupload and album creation code.

            }
            catch (OAuthException ex)
            {
                string text1 = "An error occurred retrieving the token : " + ex.Message;
            }
        }
    }

    protected void btnUploadFlicker_Click(object sender, EventArgs e)
    { 
        UploadPhotosToFlicker();
    }

    private void UploadPhotosToFlicker()
    {
        try
        {
            Flickr f = FlickrManager.GetInstance();
            OAuthRequestToken token = f.OAuthGetRequestToken(Request.Url.AbsoluteUri);
            Session["RequestToken"] = token;

            string url = f.OAuthCalculateAuthorizationUrl(token.Token, AuthLevel.Write);
            Response.Redirect(url);

            #region Commented Code

            //var popup = "window.open('" + url + "', 'popup_window', 'width=500,height=500,left=100,top=100,resizable=yes');";
            //ClientScript.RegisterStartupScript(this.GetType(), "script", popup, true);
            //Session["popup"] = popup;

            //if (Request.Cookies["OAuthToken"] != null)
            //{
            //    OAuthRequestToken requestToken = token;
            //    OAuthAccessToken accessToken = FlickrManager.OAuthToken;
            //    //FlickrManager.OAuthToken = accessToken;
            //    string thumbNailImage = Session["DirectoryPath"] + "/" + Session["ThumbNailPicfn"];
            //    string callbackThumbID = f.UploadPicture(thumbNailImage, Session["ThumbNailPicfn"].ToString(), string.Empty, string.Empty, true, false, false);
            //}
            //else
            //{
            //}

            #endregion Commented Code
        }
        catch (Exception ex)
        {
            string exp = ex.Message;
        }
    }`
```

**Comment by samjudson** [comment]
You say the token in store in the cookies, but you are never using it. My class is only meant as a guide, not as an actual implementation. However you should be using the FlickrManager.GetAuthInstance method if you already have stored the tokens.

Also note that my class only stores the token in a cookie for 1 hour.

Ideally you should split the authentication process out into a separate page, like in the sample code. Then when uploading the photo just call FlickrManager.GetAuthInstance() to get the flickr instance, and UploadPicture on that.

**Comment by msgadi** [comment]
Thanks buddy. Issue solved as per your guidance.
