### ISSUE TITLE
How to upload Video on Flickr?

### ISSUE THREAD

**Issue by msgadi** [samjudson/flickrnet-samples#2]
As I read some blog post that try Upload video using same function which is used for photo as it upload stream. I tried but I am unable to upload.

Can you please provide some inputs on this?

**Comment by samjudson** [comment]
What do you mean by unable to upload? Did you get an error?

**Comment by msgadi** [comment]
Unable to upload the video. Is there any function available so that I can upload Video using that??

**Comment by samjudson** [comment]
You need to use the UploadPicture method, exactly like you would for a photo.

If you are getting an error then please let me know what it is. I cannot help unless I can reproduce your problem.

**Comment by msgadi** [comment]
Thanks Sam, Upon using the UploadPicture Method I am able to Upload the Video.
But now the issue is, When I am trying to get the URL of uploaded Video using its callbackID/ContentID which is returned on the successful upload of the video, I am unable to get the Playable URL.

Please look at the code below I am using to get the URL..

```
Flickr flickr  = FlickrManager.GetAuthInstance();

string callbackVideoID = string.Empty;
callbackVideoID = flickr.UploadPicture(videoPath, "Test Video", "Test Vid Desc", "", true, false, false);
 PhotoInfo photoInfo =  flickr.PhotosGetInfo(callbackVideoID);
 VideoInfo videoInfo =  photoInfo.VideoInfo;
//I am not getting any playable URL here for the uploaded video.....
```

**Comment by samjudson** [comment]
If you want all the playable urls then you can use PhotosGetSizes instead.

**Comment by msgadi** [comment]
But again I am not getting what I am looking for. Actually I need the URL which ends with video extension  like .mp4 or any other video extension.
You can refer this link [here](https://www.flickr.com/groups/51035612836@N01/discuss/72157621698855558/)

**Comment by samjudson** [comment]
I don't think this information is available I'm afraid. This is not an issue with my code, but with the information supplied by the Flickr API itself.
